// ポケモンデータベース
const pokemonDatabase = {
    'ガブリアス': { jp: 'ガブリアス', types: ['ground', 'dragon'] abilities: ['さめはだ', 'すながくれ']},
    'アシレーヌ': { jp: 'アシレーヌ', types: ['water', 'fairy'] abilities: ['げきりゅう', 'うるおいボイス']},
    'マスカーニャ': { jp: 'マスカーニャ', types: ['grass', 'dark'] abilities: ['しんりょく','へんげんじざい']},
    'ブリジュラス': { jp: 'ブリジュラス', types: ['steel', 'dragon'] abilities: ['がんじょう','じきゅうりょく']},
    'ミミッキュ': { jp: 'ミミッキュ', types: ['ghost', 'fairy'] abilities: ['ばけのかわ']},
    'カバルドン': { jp: 'カバルドン', types: ['ground'] abilities: ['すなおこし']},
    'ハッサム': { jp: 'ハッサム', types: ['steel','insect'] abilities: ['テクニシャン']},
    'メガハッサム': { jp: 'メガハッサム', types: ['steel','insect'] abilities: ['テクニシャン']},
    'ギャラドス': { jp: 'ギャラドス', types: ['water', 'flying'] abilities: ['いかく','じしんかじょう']},
    'メガギャラドス': { jp: 'メガギャラドス', types: ['water', 'dark'] abilities: ['かたやぶり']},
    'マフォクシー': { jp: 'マフォクシー', types: ['fire', 'psychic'] abilities: ['マジシャン','もうか']},
    'メガマフォクシー': { jp: 'メガマフォクシー', types: ['fire', 'psychic'] abilities: ['ふゆう']},
    'カイリュー': { jp: 'カイリュー', types: ['dragon', 'flying'] abilities: ['マルチスケイル','せいしんりょく']},
    'メガカイリュー': { jp: 'メガカイリュー', types: ['dragon', 'flying'] abilities: ['マルチスケイル']},
    'メタグロス': { jp: 'メタグロス', types: ['steel', 'psychic'] abilities: ['ライトメタル','クリアボディ']},
    'メガメタグロス': { jp: 'メガメタグロス', types: ['steel', 'psychic'] abilities: ['かたいツメ']},
    'リザードン': { jp: 'リザードン', types: ['fire', 'flying'] abilities: ['もうか','サンパワー']},
    'メガリザードンY': { jp: 'リザードン', types: ['fire', 'flying'] abilities: ['ひでり']},
    'メガリザードンX': { jp: 'リザードン', types: ['fire', 'dragon'] abilities: ['かたいツメ']},
    'イダイトウ（オス）': { jp: 'イダイトウ（オス）', types: ['water', 'ghost'] abilities: ['てきおうりょく','すいすい']},
    'アーマーガア': { jp: 'アーマーガア', types: ['flying', 'steel'] abilities: ['プレッシャー','ミラーアーマー']},
    'サザンドラ': { jp: 'サザンドラ', types: ['dark', 'dragon'] abilities: ['ふゆう']},
    'ライチュウ': { jp: 'ライチュウ', types: ['electric'] abilities: ['ひらいしん','せいでんき']},
    'メガライチュウY': { jp: 'ライチュウ', types: ['electric'] abilities: ['ノーガード']},
    'メガライチュウX': { jp: 'ライチュウ', types: ['electric'] abilities: ['エレキメイカー']},
    'キラフロル': { jp: 'キラフロル', types: ['rock', 'poison'] abilities: ['ふしょく','どくげしょう']},
    'メガキラフロル': { jp: 'メガキラフロル', types: ['rock', 'poison'] abilities: ['てきおうりょく']},
    'ゲンガー': { jp: 'ゲンガー', types: ['ghost', 'poison'] abilities: ['のろわれボディ']},
    'メガゲンガー': { jp: 'メガゲンガー', types: ['ghost', 'poison'] abilities: ['かげふみ']},
    'ゲッコウガ': { jp: 'ゲッコウガ', types: ['water', 'dark'] abilities: ['げきりゅう','へんげんじざい']},
    'メガゲッコウガ': { jp: 'メガゲッコウガ', types: ['water', 'dark'] abilities: ['へんげんじざい']},
    'ウルガモス': { jp: 'ウルガモス', types: ['bug', 'fire'] abilities: ['ほのおのからだ','むしのしらせ']},
    'ドドゲザン': { jp: 'ドドゲザン', types: ['dark', 'steel'] abilities: ['そうだいしょう','まけんき','プレッシャー']},
    'バシャーモ': { jp: 'バシャーモ', types: ['fire', 'fighting'] abilities: ['もうか','かそく']},
    'メガバシャーモ': { jp: 'メガバシャーモ', types: ['fire', 'fighting'] abilities: ['もうか','かそく']},
    'サーフゴー': { jp: 'サーフゴー', types: ['steel', 'ghost'] abilities: ['','']},
    'ギルガルド': { jp: 'ギルガルド', types: ['steel', 'ghost'] abilities: ['','']},
    'ダイケンキ（ヒスイ）': { jp: 'ダイケンキ（ヒスイ）', types: ['water', 'dark'] abilities: ['','']},
    'ブラッキー': { jp: 'ブラッキー', types: ['dark'] abilities: ['','']},
    'ニンフィア': { jp: 'ニンフィア', types: ['fairy'] abilities: ['','']},
    'ムクホーク': { jp: 'ムクホーク', types: ['normal', 'flying'] abilities: ['','']},
    'ルカリオ': { jp: 'ルカリオ', types: ['fighting', 'steel'] },
    'ウォッシュロトム': { jp: 'ウォッシュロトム', types: ['electric', 'water'] abilities: ['','']},
    'ミミロップ': { jp: 'ミミロップ', types: ['normal'] abilities: ['','']},
    'フシギバナ': { jp: 'フシギバナ', types: ['grass', 'poison'] abilities: ['','']},
    'キュウコン（アローラ）': { jp: 'キュウコン（アローラ）', types: ['ice', 'fairy'] abilities: ['','']},
    'ラウドボーン': { jp: 'ラウドボーン', types: ['fire', 'ghost'] },
    'スターミー': { jp: 'スターミー', types: ['water', 'psychic'] },
    'ハラバリー': { jp: 'ハラバリー', types: ['electric'] },
    'ドヒドイデ': { jp: 'ドヒドイデ', types: ['poison', 'water'] },
    'ドラパルト': { jp: 'ドラパルト', types: ['dragon', 'ghost'] },
    'ラグラージ': { jp: 'ラグラージ', types: ['water', 'ground'] },
    'スコヴィラン': { jp: 'スコヴィラン', types: ['grass', 'fire'] },
    'ピクシー': { jp: 'ピクシー', types: ['fairy'] },
    'フラエッテ:永遠': { jp: 'フラエッテ:永遠', types: ['fairy'] },
    'ソウブレイズ': { jp: 'ソウブレイズ', types: ['fire', 'ghost'] },
    'カメックス': { jp: 'カメックス', types: ['water'] },
    'オーロンゲ': { jp: 'オーロンゲ', types: ['dark', 'fairy'] },
    'ドリュウズ': { jp: 'ドリュウズ', types: ['ground', 'steel'] },
    'バンギラス': { jp: 'バンギラス', types: ['rock', 'dark'] },
    'メガニウム': { jp: 'メガニウム', types: ['grass'] },
    'オオニューラ': { jp: 'オオニューラ', types: ['poison', 'fighting'] },
    'クチート': { jp: 'クチート', types: ['steel', 'fairy'] },
    'ペリッパー': { jp: 'ペリッパー', types: ['water', 'flying'] },
    'ペンドラー': { jp: 'ペンドラー', types: ['insect', 'poison'] },
    'エルフーン': { jp: 'エルフーン', types: ['grass', 'fairy'] },
    'ガルーラ': { jp: 'ガルーラ', types: ['normal'] },
    'マンムー': { jp: 'マンムー', types: ['ice', 'ground'] },
    'カビゴン': { jp: 'カビゴン', types: ['normal'] },
    'ウツボット': { jp: 'ウツボット', types: ['grass', 'poison'] },
    'バイバニラ': { jp: 'バイバニラ', types: ['ice'] },
    'イッカネズミ': { jp: 'イッカネズミ', types: ['normal'] },
    'クエスパトラ': { jp: 'クエスパトラ', types: ['psychic'] },
    'ヒートロトム': { jp: 'ヒートロトム', types: ['electric', 'fire'] },
    'ヤミラミ': { jp: 'ヤミラミ', types: ['dark', 'ghost'] },
    'ゾロアーク (ヒスイ)': { jp: 'ゾロアーク (ヒスイ)', types: ['normal', 'ghost'] },
    'オニシズクモ': { jp: 'オニシズクモ', types: ['water', 'insect'] },
    'バサギリ': { jp: 'バサギリ', types: ['insect', 'rock'] },
    'コノヨザル': { jp: 'コノヨザル', types: ['fighting', 'ghost'] },
    'ミロカロス': { jp: 'ミロカロス', types: ['water'] },
    'エルレイド': { jp: 'エルレイド', types: ['psychic', 'fighting'] },
    'メタモン': { jp: 'メタモン', types: ['normal'] },
    'ミミズズ': { jp: 'ミミズズ', types: ['steel'] },
    'サーナイト': { jp: 'サーナイト', types: ['psychic', 'fairy'] },
    'マリルリ': { jp: 'マリルリ', types: ['water', 'fairy'] },
    'ヌメルゴン (ヒスイ)': { jp: 'ヌメルゴン (ヒスイ)', types: ['steel', 'dragon'] },
    'ドラミドロ': { jp: 'ドラミドロ', types: ['poison', 'dragon'] },
    'エンペルト': { jp: 'エンペルト', types: ['water', 'steel'] },
    'ジャローダ': { jp: 'ジャローダ', types: ['grass'] },
    'エアームド': { jp: 'エアームド', types: ['steel', 'flying'] },
    'ジュペッタ': { jp: 'ジュペッタ', types: ['ghost'] },
    'ジュカイン': { jp: 'ジュカイン', types: ['grass'] },
    'ユキメノコ': { jp: 'ユキメノコ', types: ['ice', 'ghost'] },
    'シャンデラ': { jp: 'シャンデラ', types: ['ghost', 'fire'] },
    'ヤバソチャ': { jp: 'ヤバソチャ', types: ['grass', 'ghost'] },
    'ヤドラン': { jp: 'ヤドラン', types: ['water', 'psychic'] },
    'ブリムオン': { jp: 'ブリムオン', types: ['psychic', 'fairy'] },
    'ハリーマン': { jp: 'ハリーマン', types: ['dark', 'poison'] },
    'ビビヨン': { jp: 'ビビヨン', types: ['insect', 'flying'] },
    'エーフィ': { jp: 'エーフィ', types: ['psychic'] },
    'ローブシン': { jp: 'ローブシン', types: ['fighting'] },
    'カエンジシ': { jp: 'カエンジシ', types: ['fire', 'normal'] },
    'ガオガエン': { jp: 'ガオガエン', types: ['fire', 'dark'] },
    'ホルード': { jp: 'ホルード', types: ['normal', 'ground'] },
    'グレンアルマ': { jp: 'グレンアルマ', types: ['fire', 'psychic'] },
    'ヤドキング (ガラル)': { jp: 'ヤドキング (ガラル)', types: ['poison', 'psychic'] },
    'ポットデス': { jp: 'ポットデス', types: ['ghost'] },
    'ヘラクロス': { jp: 'ヘラクロス', types: ['insect', 'fighting'] },
    'グライオン': { jp: 'グライオン', types: ['ground', 'flying'] },
    'ウインディ (ヒスイ)': { jp: 'ウインディ (ヒスイ)', types: ['fire', 'rock'] },
    'ドデカバシ': { jp: 'ドデカバシ', types: ['normal', 'flying'] },
    'コータス': { jp: 'コータス', types: ['fire'] },
    'ラフレシア': { jp: 'ラフレシア', types: ['grass', 'poison'] },
    'イルカマン': { jp: 'イルカマン', types: ['water'] },
    'ズルズキン': { jp: 'ズルズキン', types: ['dark', 'fighting'] },
    'プテラ': { jp: 'プテラ', types: ['rock', 'flying'] },
    'シャワーズ': { jp: 'シャワーズ', types: ['water'] },
    'サメハダー': { jp: 'サメハダー', types: ['water', 'dark'] },
    'デカヌチャン': { jp: 'デカヌチャン', types: ['fairy', 'steel'] },
    'マニューラ': { jp: 'マニューラ', types: ['dark', 'ice'] },
    'ヤドラン (ガラル)': { jp: 'ヤドラン (ガラル)', types: ['poison', 'psychic'] },
    'ウェーニバル': { jp: 'ウェーニバル', types: ['water', 'fighting'] },
    'ブリガロン': { jp: 'ブリガロン', types: ['grass', 'fighting'] },
    'カイロス': { jp: 'カイロス', types: ['insect'] },
    'オーダイル': { jp: 'オーダイル', types: ['water'] },
    'ボスゴドラ': { jp: 'ボスゴドラ', types: ['steel', 'rock'] },
    'シビルドン': { jp: 'シビルドン', types: ['electric'] },
    'ヤドキング': { jp: 'ヤドキング', types: ['water', 'psychic'] },
    'イダイトウ (メス)': { jp: 'イダイトウ (メス)', types: ['water', 'ghost'] },
    'ケンタロス:炎': { jp: 'ケンタロス:炎', types: ['fighting', 'fire'] },
    'エンニュート': { jp: 'エンニュート', types: ['poison', 'fire'] },
    'ハカドッグ': { jp: 'ハカドッグ', types: ['ghost'] },
    'エレザード': { jp: 'エレザード', types: ['electric', 'normal'] },
    'フーディン': { jp: 'フーディン', types: ['psychic'] },
    'ジュナイパー (ヒスイ)': { jp: 'ジュナイパー (ヒスイ)', types: ['grass', 'fighting'] },
    'スピアー': { jp: 'スピアー', types: ['insect', 'poison'] },
    'ルガルガン (たそがれ)': { jp: 'ルガルガン (たそがれ)', types: ['rock'] },
    'ファイアロー': { jp: 'ファイアロー', types: ['fire', 'flying'] },
    'ランクルス': { jp: 'ランクルス', types: ['psychic'] },
    'ユキノオー': { jp: 'ユキノオー', types: ['grass', 'ice'] },
    'ゴウカザル': { jp: 'ゴウカザル', types: ['fire', 'fighting'] },
    'チルタリス': { jp: 'チルタリス', types: ['dragon', 'flying'] },
    'サンダース': { jp: 'サンダース', types: ['electric'] },
    'ルチャブル': { jp: 'ルチャブル', types: ['fighting', 'flying'] },
    'ジャラランガ': { jp: 'ジャラランガ', types: ['dragon', 'fighting'] },
    'バクフーン (ヒスイ)': { jp: 'バクフーン (ヒスイ)', types: ['fire', 'ghost'] },
    'デスバーン': { jp: 'デスバーン', types: ['ground', 'ghost'] },
    'オンバーン': { jp: 'オンバーン', types: ['flying', 'dragon'] },
    'バンバドロ': { jp: 'バンバドロ', types: ['ground'] },
    'アリアドス': { jp: 'アリアドス', types: ['insect', 'poison'] },
    'チリーン': { jp: 'チリーン', types: ['psychic'] },
    'グレイシア': { jp: 'グレイシア', types: ['ice'] },
    'オニゴーリ': { jp: 'オニゴーリ', types: ['ice'] },
    'ウインディ': { jp: 'ウインディ', types: ['fire'] },
    'カラマネロ': { jp: 'カラマネロ', types: ['dark', 'psychic'] },
    'ワルビアル': { jp: 'ワルビアル', types: ['ground', 'dark'] },
    'ケケンカニ': { jp: 'ケケンカニ', types: ['fighting', 'ice'] },
    'ピジョット': { jp: 'ピジョット', types: ['normal', 'flying'] },
    'キュウコン': { jp: 'キュウコン', types: ['fire'] },
    'ドダイトス': { jp: 'ドダイトス', types: ['grass', 'ground'] },
    'ヘルガー': { jp: 'ヘルガー', types: ['dark', 'fire'] },
    'チャーレム': { jp: 'チャーレム', types: ['fighting', 'psychic'] },
    'デンリュウ': { jp: 'デンリュウ', types: ['electric'] },
    'ハガネール': { jp: 'ハガネール', types: ['steel', 'ground'] },
    'ミカルゲ': { jp: 'ミカルゲ', types: ['ghost', 'dark'] },
    'ブロスター': { jp: 'ブロスター', types: ['water'] },
    'ニョロトノ': { jp: 'ニョロトノ', types: ['water'] },
    'デスカーン': { jp: 'デスカーン', types: ['ghost'] },
    'アマージョ': { jp: 'アマージョ', types: ['grass'] },
    'カットロトム': { jp: 'カットロトム', types: ['electric', 'grass'] },
    'クレッフィ': { jp: 'クレッフィ', types: ['steel', 'fairy'] },
    'カイリキー': { jp: 'カイリキー', types: ['fighting'] },
    'ペロリーム': { jp: 'ペロリーム', types: ['fairy'] },
    'モルペコ': { jp: 'モルペコ', types: ['electric', 'dark'] },
    'キョジオーン': { jp: 'キョジオーン', types: ['rock'] },
    'ガメノデス': { jp: 'ガメノデス', types: ['rock', 'water'] },
    'フォレトス': { jp: 'フォレトス', types: ['insect', 'steel'] },
    'ピカチュウ': { jp: 'ピカチュウ', types: ['electric'] },
    'アブソル': { jp: 'アブソル', types: ['dark'] },
    'カミツオロチ': { jp: 'カミツオロチ', types: ['grass', 'dragon'] },
    'エンブオー': { jp: 'エンブオー', types: ['fire', 'fighting'] },
    'オーロット': { jp: 'オーロット', types: ['ghost', 'grass'] },
    'ヌメルゴン': { jp: 'ヌメルゴン', types: ['dragon'] },
    'ロズレイド': { jp: 'ロズレイド', types: ['grass', 'poison'] },
    'ゴルーグ': { jp: 'ゴルーグ', types: ['ground', 'ghost'] },
    'ゾロアーク': { jp: 'ゾロアーク', types: ['dark'] },
    'ドサイドン': { jp: 'ドサイドン', types: ['ground', 'rock'] },
    'ケンタロス:水': { jp: 'ケンタロス:水', types: ['fighting', 'water'] },
    'クレベース': { jp: 'クレベース', types: ['ice'] },
    'ムシャーナ': { jp: 'ムシャーナ', types: ['psychic'] },
    'リキキリン': { jp: 'リキキリン', types: ['normal', 'psychic'] },
    'リーフィア': { jp: 'リーフィア', types: ['grass'] },
    'ジジーロン': { jp: 'ジジーロン', types: ['normal', 'dragon'] },
    'レパルダス': { jp: 'レパルダス', types: ['dark'] },
    'サダイジャ': { jp: 'サダイジャ', types: ['ground'] },
    'マホイップ': { jp: 'マホイップ', types: ['fairy'] },
    'アーボック': { jp: 'アーボック', types: ['poison'] },
    'トリデプス': { jp: 'トリデプス', types: ['rock', 'steel'] },
    'ゴロンダ': { jp: 'ゴロンダ', types: ['fighting', 'dark'] },
    'アマルルガ': { jp: 'アマルルガ', types: ['rock', 'ice'] },
    'タブンネ': { jp: 'タブンネ', types: ['normal'] },
    'ガチゴラス': { jp: 'ガチゴラス', types: ['rock', 'dragon'] },
    'ライボルト': { jp: 'ライボルト', types: ['electric'] },
    'ブースター': { jp: 'ブースター', types: ['fire'] },
    'ニャオニクス (オス)': { jp: 'ニャオニクス (オス)', types: ['psychic'] },
    'ドクロッグ': { jp: 'ドクロッグ', types: ['poison', 'fighting'] },
    'エモンガ': { jp: 'エモンガ', types: ['electric', 'flying'] },
    'フラージェス': { jp: 'フラージェス', types: ['fairy'] },
    'バクフーン': { jp: 'バクフーン', types: ['fire'] },
    'パンプジン (ギガだま)': { jp: 'パンプジン (ギガだま)', types: ['ghost', 'grass'] },
    'タイレーツ': { jp: 'タイレーツ', types: ['fighting'] },
    'ツンベアー': { jp: 'ツンベアー', types: ['ice'] },
    'バリコオル': { jp: 'バリコオル', types: ['ice', 'psychic'] },
    'バクーダ': { jp: 'バクーダ', types: ['fire', 'ground'] },
    'フロストロトム': { jp: 'フロストロトム', types: ['electric', 'ice'] },
    'クレベース (ヒスイ)': { jp: 'クレベース (ヒスイ)', types: ['ice', 'rock'] },
    'レントラー': { jp: 'レントラー', types: ['electric'] },
    'マッギョ': { jp: 'マッギョ', types: ['ground', 'electric'] },
    'ラムパルド': { jp: 'ラムパルド', types: ['rock'] },
    'アヤシシ': { jp: 'アヤシシ', types: ['normal', 'psychic'] },
    'ジュナイパー': { jp: 'ジュナイパー', types: ['grass', 'ghost'] },
    'ライチュウ (アローラ)': { jp: 'ライチュウ (アローラ)', types: ['electric', 'psychic'] },
    'ニャオニクス (メス)': { jp: 'ニャオニクス (メス)', types: ['psychic'] },
    'トリミアン': { jp: 'トリミアン', types: ['normal'] },
    'スピンロトム': { jp: 'スピンロトム', types: ['electric', 'flying'] },
    'ケンタロス': { jp: 'ケンタロス', types: ['fighting'] },
    'タルップル': { jp: 'タルップル', types: ['grass', 'dragon'] },
    'デデンネ': { jp: 'デデンネ', types: ['electric', 'fairy'] },
    'ダストダス': { jp: 'ダストダス', types: ['poison'] },
    'マッギョ (ガラル)': { jp: 'マッギョ (ガラル)', types: ['ground', 'steel'] },
    'ハリーセン': { jp: 'ハリーセン', types: ['water', 'poison'] },
    'アップリュー': { jp: 'アップリュー', types: ['grass', 'dragon'] },
    'ダイケンキ': { jp: 'ダイケンキ', types: ['water'] },
    'ルガルガン (まひる)': { jp: 'ルガルガン (まひる)', types: ['rock'] },
    'ヒヤッキー': { jp: 'ヒヤッキー', types: ['water'] },
    'ルガルガン (まよなか)': { jp: 'ルガルガン (まよなか)', types: ['rock'] },
    'バオッキー': { jp: 'バオッキー', types: ['fire'] },
    'ヤレユータン': { jp: 'ヤレユータン', types: ['normal', 'psychic'] },
    'パンプジン (ちゅうだま)': { jp: 'パンプジン (ちゅうだま)', types: ['ghost', 'grass'] },
    'ナゲツケサル': { jp: 'ナゲツケサル', types: ['fighting'] },
    'パンプジン (こだま)': { jp: 'パンプジン (こだま)', types: ['ghost', 'grass'] },
    'パンプジン (おおだま)': { jp: 'パンプジン (おおだま)', types: ['ghost', 'grass'] },
    'ロトム': { jp: 'ロトム', types: ['electric', 'ghost'] },
    'フレフワン': { jp: 'フレフワン', types: ['fairy'] },
    'ヤナッキー': { jp: 'ヤナッキー', types: ['grass'] },
    'ミルホッグ': { jp: 'ミルホッグ', types: ['normal'] },
    'ポワルン': { jp: 'ポワルン', types: ['normal'] },
    'ケンタロス:格': { jp: 'ケンタロス:格', types: ['fighting'] }
};

// ポケモンリスト
const pokemonList = Object.keys(pokemonDatabase);

// タイプリスト（ひらがなのみ）
const typeList = [
    { jp: 'ノーマル', en: 'normal' },
    { jp: 'ほのお', en: 'fire' },
    { jp: 'みず', en: 'water' },
    { jp: 'でんき', en: 'electric' },
    { jp: 'くさ', en: 'grass' },
    { jp: 'こおり', en: 'ice' },
    { jp: 'かくとう', en: 'fighting' },
    { jp: 'どく', en: 'poison' },
    { jp: 'じめん', en: 'ground' },
    { jp: 'ひこう', en: 'flying' },
    { jp: 'エスパー', en: 'psychic' },
    { jp: 'むし', en: 'insect' },
    { jp: 'いわ', en: 'rock' },
    { jp: 'ゴースト', en: 'ghost' },
    { jp: 'ドラゴン', en: 'dragon' },
    { jp: 'あく', en: 'dark' },
    { jp: 'はがね', en: 'steel' },
    { jp: 'フェアリー', en: 'fairy' }
];

// カタカナをひらがなに変換する関数
function toHiragana(text) {
    const katakanaMap = {
        'ガ': 'が', 'ギ': 'ぎ', 'グ': 'ぐ', 'ゲ': 'げ', 'ゴ': 'ご',
        'カ': 'か', 'キ': 'き', 'ク': 'く', 'ケ': 'け', 'コ': 'こ',
        'サ': 'さ', 'シ': 'し', 'ス': 'す', 'セ': 'せ', 'ソ': 'そ',
        'ザ': 'ざ', 'ジ': 'じ', 'ズ': 'ず', 'ゼ': 'ぜ', 'ゾ': 'ぞ',
        'タ': 'た', 'チ': 'ち', 'ツ': 'つ', 'テ': 'て', 'ト': 'と',
        'ダ': 'だ', 'ヂ': 'ぢ', 'ヅ': 'づ', 'デ': 'で', 'ド': 'ど',
        'ナ': 'な', 'ニ': 'に', 'ヌ': 'ぬ', 'ネ': 'ね', 'ノ': 'の',
        'ハ': 'は', 'ヒ': 'ひ', 'フ': 'ふ', 'ヘ': 'へ', 'ホ': 'ほ',
        'バ': 'ば', 'ビ': 'び', 'ブ': 'ぶ', 'ベ': 'べ', 'ボ': 'ぼ',
        'パ': 'ぱ', 'ピ': 'ぴ', 'プ': 'ぷ', 'ペ': 'ぺ', 'ポ': 'ぽ',
        'マ': 'ま', 'ミ': 'み', 'ム': 'む', 'メ': 'め', 'モ': 'も',
        'ヤ': 'や', 'ユ': 'ゆ', 'ヨ': 'よ',
        'ラ': 'ら', 'リ': 'り', 'ル': 'る', 'レ': 'れ', 'ロ': 'ろ',
        'ワ': 'わ', 'ヲ': 'を', 'ン': 'ん',
        'ア': 'あ', 'イ': 'い', 'ウ': 'う', 'エ': 'え', 'オ': 'お'
    };
    
    let result = '';
    for (let char of text) {
        result += katakanaMap[char] || char;
    }
    return result;
}
